<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-06T12:04:08Z" name="Suite" finished-at="2023-01-06T12:05:23Z" duration-ms="75696">
    <groups>
    </groups>
    <test started-at="2023-01-06T12:04:08Z" name="Test" finished-at="2023-01-06T12:05:23Z" duration-ms="75696">
      <class name="sauceTest.SauceTest">
        <test-method is-config="true" signature="logpath()[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:08Z" name="logpath" finished-at="2023-01-06T12:04:08Z" duration-ms="361" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logpath -->
        <test-method is-config="true" signature="testSetup()[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:08Z" name="testSetup" finished-at="2023-01-06T12:04:22Z" duration-ms="13498" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method signature="loginuser1()[pri:1, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:22Z" name="loginuser1" finished-at="2023-01-06T12:04:24Z" duration-ms="2525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginuser1 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:24Z" name="getResult" finished-at="2023-01-06T12:04:25Z" duration-ms="1036" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginuser1 status=SUCCESS method=SauceTest.loginuser1()[pri:1, instance:sauceTest.SauceTest@202b0582] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="testSetup()[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:25Z" name="testSetup" finished-at="2023-01-06T12:04:29Z" duration-ms="3904" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method signature="loginuser2()[pri:2, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:29Z" name="loginuser2" finished-at="2023-01-06T12:04:50Z" duration-ms="20770" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at sauceTest.SauceTest.validation(SauceTest.java:114)
at sauceTest.SauceTest.login(SauceTest.java:107)
at sauceTest.SauceTest.loginuser2(SauceTest.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginuser2 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:50Z" name="getResult" finished-at="2023-01-06T12:04:51Z" duration-ms="1312" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginuser2 status=FAILURE method=SauceTest.loginuser2()[pri:2, instance:sauceTest.SauceTest@202b0582] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="testSetup()[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:51Z" name="testSetup" finished-at="2023-01-06T12:04:55Z" duration-ms="3903" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method signature="loginuser3()[pri:3, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:55Z" name="loginuser3" finished-at="2023-01-06T12:04:56Z" duration-ms="843" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginuser3 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:56Z" name="getResult" finished-at="2023-01-06T12:04:57Z" duration-ms="984" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginuser3 status=SUCCESS method=SauceTest.loginuser3()[pri:3, instance:sauceTest.SauceTest@202b0582] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="testSetup()[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:04:57Z" name="testSetup" finished-at="2023-01-06T12:05:01Z" duration-ms="3931" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method signature="loginuser4()[pri:4, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:05:01Z" name="loginuser4" finished-at="2023-01-06T12:05:22Z" duration-ms="20736" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at sauceTest.SauceTest.validation(SauceTest.java:114)
at sauceTest.SauceTest.login(SauceTest.java:107)
at sauceTest.SauceTest.loginuser4(SauceTest.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginuser4 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:05:22Z" name="getResult" finished-at="2023-01-06T12:05:23Z" duration-ms="1384" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginuser4 status=FAILURE method=SauceTest.loginuser4()[pri:4, instance:sauceTest.SauceTest@202b0582] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:sauceTest.SauceTest@202b0582]" started-at="2023-01-06T12:05:23Z" name="teardown" finished-at="2023-01-06T12:05:23Z" duration-ms="445" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- sauceTest.SauceTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
